#+STARTUP: showall indentX
#+STARTUP: hidestars
#+OPTIONS: num:nil tags:nil toc:nil timestamps:nil \n:t
#+BEGIN_EXPORT html
---
layout: default
title: The brief case for userspace networking
date: 2019-02-01 00:00:00 +0000
tags: DPDK VPP FOSDEM LINUX
---
#+END_EXPORT

I wrote a [[https://www.fosdem.org][FOSDEM 2019]] lighting talk on [[https://archive.fosdem.org/2019/schedule/event/userspace_network_stacks/][the brief case for userspace networking]].
The talk briefly describes the rationale, origins and ecosystem of userspace
networking tooling such as DPDK, FD.io VPP and similar tools. Having been
involved with most of them since their inception, I thought that I was well
placed to discuss this. I was pretty pleased with the final presentation.

I think what was on my mind, what I was responding to in my own way, was to
degrees of hositility I had experienced towards to these tools and their
communities over the years, that I never really understood. Terms like 'kernel
bypass networking' carried negatives connotations that I didn't agree with and
that bothered me. For me, open source is the eternal [[https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar][bazaar]], and that means that
some degree of duplication is always inevitable in order for innovation to take
place. Although I do understand, why it can cause friction at times.

The willingness to fork, and try something in a new and different way, is open
source's great asset and the reason while open source solutions usually prevail.
Userspace networking has been enabling this model for engineers writing network
functions for the past 10+ years. [[https://ebpf.io/][eBPF]] is doing a remarkable job enabling the
same for kernel based networking today.

When I had to leave FOSDEM early, the talk itself was relegated to the graveyard
shift, but it lives on [[https://archive.fosdem.org/2019/schedule/event/userspace_network_stacks/][online]].
